export const clickbaity_outlines = [
	'10 Ways to Transform Your Life Overnight',
	"You Won't Believe What Happened Next!",
	'The Secret Hack Every Blogger Should Know',
	'Why Everyone is Talking About This...',
	'Is This the Best Thing Since Sliced Bread?',
	'5 Tips to Boost Your Productivity Instantly',
	'How to Achieve Your Wildest Dreams',
	'The Truth About Coding Revealed',
	'What No One Tells You About Coding',
	'Don’t Miss Out on These Amazing Tricks!',
	'The Ultimate Guide to Coding',
	'Discover the Hidden Gems of Coding',
	'How to Master Coding Like a Pro',
	'Top 7 Myths About Coding Debunked',
	'The One Thing You Need to Know About Coding',
	'Amazing Facts About Coding You Never Knew',
	'Success Stories: How Coding Changed Lives',
	'Why Coding is Trending Right Now',
	"The Do's and Don'ts of Coding",
	'Insider Secrets to Mastering Coding'
];
