<script>
	import Content from '$lib/Content.svelte';
</script>

<Content>
	<div class="xs:p-2 space-y-4 p-8">
		<h1>Hi there 👋 I'm mikkelam.</h1>
		<p>
			I'm not really sure how I want to use this website <em>just yet</em>. However, here's some
			background info about me:
		</p>
		<p />

		<p class="pt-4">
			I am deep believer in technology <em>and</em> people. I am deeply curious in nature and I love
			learning and doing. I want to be part of a future that I like and I want to help shape it. I think
			that the world is scary and unpredictable but it doesn't have to be. I am still looking for my
			place in the world and will probably continue that quest until my demise.
		</p>

		<p>
			I've recently started to appreciate reading and have been consuming a ton of amazing books. I
			might have a book section later where I add and sort through some favorites and suggestions.
		</p>
		<p>
			I've built this blog to motivate myself to write down my thoughts more and because it was a
			fun challenge. I like the 2000-esque style of making your own unique blog. I've built this
			page using SvelteKit and MDsveX (which enabled a nice mix of markdown/svelte writing).
			TailwindCSS is for styling. If you're interested in reading the source code. It can be found
			<a class="link" href="https://github.com/mikkelam/mikkelam.com">here</a>
		</p>

		<p>Here's my favorite quote from Mark Twain</p>
		<div class="ml-4 rounded-md bg-gray-200 px-4 py-2">
			<q class="italic">
				I do not fear death. I had been dead for billions and billions of years before I was born,
				and had not suffered the slightest inconvenience from it.
			</q>
		</div>

		<p class="pt-10 text-sm text-green-600">
			You can contact me at this address <a class="link" href="mailto:tangled-stadia0y@icloud.com"
				>tangled-stadia0y@icloud.com</a
			> - it is an autogenerated forwarder to preserve my privacy.
		</p>
		<p class="text-right text-sm text-gray-400">Last updated Sat Jul 20 15:19:42 CEST 2024</p>
	</div>
</Content>
