<script>
	import Content from '$lib/Content.svelte';
</script>

<Content>
	<div class="p-8 xs:p-2 space-y-4 ">
		<h1>Hi there 👋 I'm Mikkel A. Madsen</h1>
		<p>
			I'm not really sure how I want to use this website <em>just yet</em>. However, here's some
			background info about me:
		</p>
		<p />

		<p class="pt-4">
			I am deep believer in technology <em>and</em> people. I am deeply curious in nature and I love
			learning and doing. I want to be part of a future that I like and I want to help shape it. I think
			that the world is scary and unpredictable but it doesn't have to be. I am still looking for my
			place in the world and will probably continue that quest until my demise.
		</p>
		<p>
			In my work life I have mainly worked with startup companies. I have helped shape a few from
			the beginning. I am currently employed at a robotics company building laboratory robots called <a
				class="link"
				href="https://reshapebiotech.com">Reshape Biotech</a
			>
			and I'm loving it. I thrive in opportunities where i can help build cool products that solve
			<em>real problems</em>. At reshape, I especially enjoy the diversity of the software stack,
			that I get to work with as well as the people that work there. Building physical products is
			<em>fucking hard.</em>
		</p>

		<p>
			I've recently started to appreciate reading and have been consuming a ton of amazing books. I
			might have a book section later where I add and sort through some favorites and suggestions.
		</p>

		<p>Here's my favorite quote from Mark Twain</p>
		<div class="bg-gray-200 ml-4 py-2 px-4 rounded-md">
			<q class="italic ">
				I do not fear death. I had been dead for billions and billions of years before I was born,
				and had not suffered the slightest inconvenience from it.
			</q>
		</div>

		<p class="text-sm pt-10 text-green-600">
			You can contact me at this address <a class="link" href="mailto:tangled-stadia0y@icloud.com"
				>tangled-stadia0y@icloud.com</a
			> - it is an autogenerated forwarder to preserve my privacy.
		</p>
		<p class="text-gray-400 text-sm text-right">Last updated 02/11/2021</p>
	</div>
</Content>
